config/routes.rb
PickUpSports::Application.routes.draw do
 
  devise_for :users
  devise_for :users do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  resources :sports do
    member do
      post :attend
    end
  end
  root :to => 'sports#index'

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  attr_accessible :address, :game, :latitude, :longitude, :needed, :zipcode, :state, :user_id

  geocoded_by :geolocate
  after_validation :geocode

  belongs_to :user
  # validates_numericality_of :needed, :greater_than => 0
  def geolocate
     "#{self.address}"', '"#{self.state}"', '"#{self.zipcode}"
  end

  def self.search(search)
    if search
      #uses active record to search database for gametypes with regular expression
        find(:all, :conditions => ['game LIKE ?', "%#{search}"])
    else
        find(:all)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :avatar, :username
  mount_uploader :avatar, AvatarUploader

  has_many :sports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  
  def index
    @sports = Sport.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sports }
    end
  end

  def show
    @sport = Sport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sport }
    end
  end

  def new
    @sport = Sport.new
    @sport.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sport }
    end
  end


  def create
    @sport = Sport.new(params[:sport])
    #saves the user as the current user when created
    @sport.user = current_user
    
    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render json: @sport, status: :created, location: @sport }
      else
        format.html { render action: "new" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sports/1
  # PUT /sports/1.json
  def update
    @sport = Sport.find(params[:id])

    respond_to do |format|
      if @sport.update_attributes(params[:sport])
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sport = Sport.find(params[:id])
    @sport.destroy

    respond_to do |format|
      format.html { redirect_to sports_url }
      format.json { head :no_content }
    end
  end

  def attend
    @sport = Sport.find(params[:id])
    if @sport.needed > 1
      @sport.needed = @sport.needed - 1
      @sport.save
      render :partial => 'update_attend_count', :locals => { :sport => @sport }
    else
      # @sport.destroy
      render :partial => 'delete_row', :locals => { :sport => @sport}
      @sport.destroy
    end
     
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PickUpSports</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCmG5AMSt0spzB0RWDAGFTiVO_L28T3k94&sensor=false">
</script>
<script>
$(function() {
  setMap();
  <% Sport.all.each do |t| %>
  addMarker(<%= t.latitude %>, <%= t.longitude %>, "<%= t.game %>");
  <% end %>
});
</script>

<body>
<nav class="top-bar">
<span>
  <div class="sportable">
    Sportable
  </div>
  <div class="login">
      <% if user_signed_in? %> 
           <%= image_tag current_user.avatar.thumb.url, :class => "login-thumb" %> <%= current_user.username %> 
          <%= link_to "Sign out", destroy_user_session_path %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path%> or <%= link_to "Sign in", new_user_session_path%>
      <% end %> 
  </div>
</span>
</nav>

<img src="assets/streetball.jpg" class="street"> 

<%= yield %>

<br><br><br>
<div id="map-canvas"/>
</body>
</html>

app/views/sports/_delete_row.js.erb
$('#sport-<%=sport.id%>').fadeOut('slow');

app/views/sports/_form.html.erb
<%= form_for Sport.new(:user_id => current_user.id) do |f| %>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
    <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
    <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :needed %><br />
    <%= f.number_field :needed %>
  </div>
  <div class="field">
    <%= f.label :game %><br />
    <%= f.text_field :game %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sports/_update_attend_count.js.erb
$('#needed-<%=sport.id %>').html(<%=sport.needed%>);

app/views/sports/attend.js.erb
//find url using jquery selector
//rendered by controller when you delete it

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<h1></h1>
<div class="search-section">
  <%= form_tag sports_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search], :class => "search" %>
      <%= submit_tag "Search", :name => nil, :class => "button" %>
  <% end %>
</div>
<table>
  <tr>
    <th>Posted by</th>
    <th>Game</th>
    <th>Where</th>
    <th>Needed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sports.each do |sport| %>
  <tr id="sport-<%=sport.id%>">
    <td><%= image_tag sport.user.avatar.thumb.url, :class => "login-thumb" %><%= sport.user.username %></td>
    <td><%= sport.game %></td>    
    <td><%= sport.address %></td>
    <td id="needed-<%=sport.id%>"><%= sport.needed %></td>
    <td><%= button_to 'Attend', attend_sport_path(sport), :class => "tiny button", remote: true %></td>
    <!-- removed remote true dont forget to add it in -->
  </tr>
<% end %>
</table>

<br/>

<!-- modal foundation code -->
<div class="create-game-button">
  <a href="#" data-reveal-id="myModal"><button type="button">Create Game</button></a>
  <div id="myModal" class="reveal-modal">
    <h2>Create a Game</h2>
    <p><%= render 'form' %></p>
    <a class="close-reveal-modal">&#215;</a>
  </div>
</div>

app/views/sports/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @sport.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @sport.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @sport.longitude %>
</p>

<p>
  <b>Needed:</b>
  <%= @sport.needed %>
</p>

<p>
  <b>Game:</b>
  <%= @sport.game %>
</p>



<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>